services:
  db:
    image: neo4j:4.4.15-community
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      internal:
        ipv4_address: 172.24.0.10
    volumes:
      - $PWD/neo4j_mount/data:/data
      - $PWD/neo4j_mount/logs:/logs
      - $PWD/neo4j_mount/conf:/conf
      - $PWD/plugins:/plugins
      - $PWD/files:/files
    environment:
      - NEO4J_AUTH=neo4j/test
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4JLABS_PLUGINS=\[\"apoc\"\]
    deploy:
      resources:
        limits:
          memory: 4g

  app:
    image: neo4jtp:latest
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - $PWD/dblpv13.json:/file.json
      - $PWD/files:/files
    environment:
      - JSON_FILE=/file.json
      - MAX_NODES=5000
      - NEO4J_IP=172.24.0.10 # must be the same as above
      - FILES_FOLDER=/files
    deploy:
      resources:
        limits:
          memory: 4g

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "172.24.0.0/24"
